name: Run Unit Tests

on: push

jobs:
  unit_test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      
      - name: Test with Coverage
        run: ./gradlew jacocoTestReport
      
      - name: Unit Test results
        uses: actions/upload-artifact@v2
        with:
          name: unit-test-report
          path: shared/build/reports/tests/testDebugUnitTest
      
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: shared/build/reports/jacoco/jacocoTestReport

      - name: Download Test Reports Folder
        uses: actions/download-artifact@v2
        with:
          name: codecov report
          path: shared/build/reports/jacoco/jacocoTestReport

      - name: Upload Test Report
        run:  bash <(curl -s https://codecov.io/bash) -f "shared/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml"

